toolbar:
  - styleselect | bold italic | alignleft aligncenter alignright alignjustify,
  - bullist numlist outdent indent | link image | code | codesample,
plugins:
  - image
  - link
  - code
  - codesample
  - autoresize
  - imagetools
  - media
  - table
  - insertdatetime
  - charmap
  - print
  - preview
  - anchor
  - searchreplace
  - visualblocks
  - fullscreen